sudo: false
dist: trusty

language: php

branches:
  only:
    - master

cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.7 WP_MULTISITE=0
  - WP_VERSION=4.6 WP_MULTISITE=0
  - WP_VERSION=4.5 WP_MULTISITE=0
  - WP_VERSION=4.4 WP_MULTISITE=0
  - WP_VERSION=4.3 WP_MULTISITE=0
  - WP_VERSION=4.2 WP_MULTISITE=0
  - WP_VERSION=4.1 WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0

matrix:
  exclude:
    - php: 5.3
      dist: trusty
  include:
    - php: 5.3
      sudo: required
      dist: precise
    - php: 5.6
      env: TRAVISCI=phpcs
  allow_failures:
    - php: 5.6
      env: TRAVISCI=phpcs
  fast_finish: true

before_script:
  - |
    # Remove Xdebug for a huge performance increase:
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    # Export Composer's global bin dir to PATH:
    composer config --list --global
    export PATH=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }/vendor/bin:$PATH"; }`
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      # Install the specified version of PHPUnit depending on the PHP version:
      if [[ "$WP_TRAVISCI" == "travis:phpunit" ]]; then
        case "$TRAVIS_PHP_VERSION" in
          7.2|7.1|7.0|nightly)
            echo "Using PHPUnit 6.x"
            composer global require "phpunit/phpunit:^6"
            ;;
          5.6|5.5|5.4|5.3)
            echo "Using PHPUnit 4.x"
            composer global require "phpunit/phpunit:^4"
            ;;
          *)
            echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
            exit 1
            ;;
        esac
      fi
    fi
  - |
    if [[ "$TRAVISCI" == "phpcs" ]] ; then
      composer install
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      # Run PHPUnit tests
      phpunit || exit 1
      # WP_MULTISITE=1 phpunit || exit 1
    fi
  - |
    if [[ "$TRAVISCI" == "phpcs" ]] ; then
      ./vendor/bin/phpcs
    fi

notifications:
  email:
    on_start: never
    on_failure: always
    on_success: change
    on_pull_requests: false
