sudo: false
dist: trusty

language: php

notifications:
  email:
    on_start: never
    on_failure: always
    on_success: change
    on_pull_requests: false

branches:
  only:
    - master

cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.5
      env: WP_VERSION=latest
    - php: 5.4
      env: WP_VERSION=latest
    - php: 5.3
      sudo: required
      dist: precise
      env: WP_VERSION=latest
    - php: 5.6
      env: TRAVISCI=phpcs
  allow_failures:
    - php: 5.6
      env: TRAVISCI=phpcs

before_script:
  - |
    export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then
        mkdir -p $HOME/phpunit-bin
        wget -O $HOME/phpunit-bin/phpunit https://phar.phpunit.de/phpunit-4.8.phar
        chmod +x $HOME/phpunit-bin/phpunit
        export PATH=$PATH:$HOME/phpunit-bin/
      else
        composer global require "phpunit/phpunit=6.*"
      fi
    fi
  - |
    if [[ "$TRAVISCI" == "phpcs" ]] ; then
      composer install
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      # Run PHPUnit tests
      phpunit || exit 1
      WP_MULTISITE=1 phpunit || exit 1
    fi
  - |
    if [[ "$TRAVISCI" == "phpcs" ]] ; then
      ./vendor/bin/phpcs
    fi
