sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.phpbrew

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest SWITCH_TO_PHP=5.3
    - php: 5.6
      env: TRAVISCI=phpcs

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      set -e
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      source bin/install-php-phpunit.sh
      set +e
    fi
  - |
    if [[ "$TRAVISCI" == "phpcs" ]] ; then
      composer install
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      echo Running with the following versions:
      php -v
      phpunit --version
      # Run PHPUnit tests
      phpunit || exit 1
      WP_MULTISITE=1 phpunit || exit 1
    fi
  - |
    if [[ "$TRAVISCI" == "phpcs" ]] ; then
      ./vendor/bin/phpcs
    fi
